### ISSUE TITLE
Improve Slicing that info entry[x] warnings are not shown

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-orf#108]
see also here: https://github.com/hl7ch/ch-emed/issues/106

**Comment by ziegm** [comment]
@pjolo please review and close issue if it is okay.
* [Profile](http://build.fhir.org/ig/hl7ch/ch-orf/branches/master/StructureDefinition-ch-orf-document.html)
* [QA](http://build.fhir.org/ig/hl7ch/ch-orf/branches/master/qa.html)

**Comment by pjolo** [comment]
Checked and closed
