### ISSUE TITLE
Date, the document was created

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-orf#11]
According to Issue #10 

The date the document was created is currently defined as Composition.date.
Would it make sense to define it as Bundle.timestamp because the identifier of the document has now changed to Bundle.identifier?

**Comment by oliveregger** [comment]
Compositon.date is editing time and Bundle.timestamp is when the bundle was assembled.

-> Bundle.timestamp would be the best fit for the date, the document was created.

**Comment by oliveregger** [comment]
will be adpated, telco form 3.3.
