### ISSUE TITLE
mapping and linkId's

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-orf#113]
with the latest PR some linkId's are not consistent:

1. familydoctor.practitioner / familydoctor.practitioner.organization
why not familydoctor.practitionerRole, familydoctor.practitionerRole.practitioner and  familydoctor.practitioner.organization as with other form entries?

2. antecedentEpisodeOfCare.practitionerRole.organization.name
practitionerRole should be removed?

the new items are not yet added to the mapping document:
https://docs.google.com/spreadsheets/d/1e1pQsHjgHSIKiMhTYLdXTpaGPRONcdn2hYOeb2LNwrY/edit#gid=0

new questionnaire items since 1.0.0:

initiator
initiator.legalguardian
initiator.initiatorrelation
initiator.practitionerRole
initiator.practitionerRole.practitioner.*
initiator.practitionerRole.organization.*
initiator.relatedPerson.*
patient.languageOfCorrespondence
familydoctor
familydoctor.practitioner.*
familydoctor.practitioner.organization-*
antecedentEpisodeOfCare
antecedentEpisodeOfCare.start
antecedentEpisodeOfCare.end
antecedentEpisodeOfCare.organization
antecedentEpisodeOfCare.practitionerRole.organization.name
antecedentEpisodeOfCare.organization.streetAddressLine
antecedentEpisodeOfCare.organization.postalCode
antecedentEpisodeOfCare.organization.city
antecedentEpisodeOfCare.organization.country
consent
consent.statement
consent.statement.note

**Comment by oliveregger** [comment]
Für Initiator, familydoctor, antecedentEpisodeOfCare sowie consent gibt es keine QuestionnaireResponse Beispiele.

**Comment by JBleuer** [comment]
1) with the latest PR some linkId's are not consistent:

    familydoctor.practitioner / familydoctor.practitioner.organization
    why not familydoctor.practitionerRole, familydoctor.practitionerRole.practitioner and familydoctor.practitioner.organization as with other form entries?

Only "receiver Copy" has"role". As discussed in telco, we leave it like it is

2) corrected.

items are in mapping document.

**Comment by JBleuer** [comment]
is now committed

**Comment by pjolo** [comment]
checked and issue closed
