### ISSUE TITLE
CH ORF Consent - Required elements from Consent resource should be specified

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-orf#115]
ch.fhir.ig.ch-orf#1.1.0 /StructureDefinition-ch-orf-consent.html

The base Consent resource has http://hl7.org/fhir/R4/consent.html

- status	code	draft | proposed | active | rejected | inactive | entered-in-error
- scope	  1..1	CodeableConcept	 
- category 1..*	CodeableConcept

For the CH ORF Consent this values should be fixed/specified.

**Comment by oliveregger** [comment]
in addition following constraint needs to be met: ppc-1: 'Either a Policy or PolicyRule' Rule 'Either a Policy or PolicyRule' Failed

**Comment by JBleuer** [comment]
Now committed

**Comment by pjolo** [comment]
checked and issue closed
