### ISSUE TITLE
CodeableConcet or Coding in extension for CH:ORF?

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#116]
ch.fhir.ig.ch-orf#1.1.0 /StructureDefinition-ch-orf-initiator.html

http://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-initiator.html

ch-orf-personalrelation and ch-orf-legalrelation are defined as CodeableConcept, the input from the form is however only Coding, should the value be instead valueCoding for those elements?

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
this would apply also to http://fhir.ch/ig/ch-orf/StructureDefinition/ch-orf-consentcode

**Comment by JBleuer** [comment]
Is now committed

**Comment by pjolo** [comment]
checked issue closed
