### ISSUE TITLE
Questionnaire Order-Referral-Form: consent 0..* in From (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#117]
ch.fhir.ig.ch-orf#1.1.0 /Questionnaire-order-referral-form.html

consent can be added multiple times in the form ( consent	Einverständniserklärung	0..*) however  the extension patientConsent is only allowed once in the composition: http://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-composition.html#Composition.extension:patientConsent, the cardinalities should be the same.

Oliver Egger, ahdis ag

**Comment by JBleuer** [comment]
now committed
