### ISSUE TITLE
Update documentation (Home)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-orf#119]
Based on the adjustments in the composition, the documentation on the home page should also be adjusted:
* http://build.fhir.org/ig/hl7ch/ch-orf/index.html#volume-3--content-modules
   * http://build.fhir.org/ig/hl7ch/ch-orf/index.html#generic-elements-of-a-questionnaire
   * http://build.fhir.org/ig/hl7ch/ch-orf/index.html#healthcare-domain-specific-elements-of-a-questionnaire

**Comment by JBleuer** [comment]
Updated Table 7: Added new items.
Changed order according to order of items in questionnaire.
Changed "..lists the generic given elements" to "...lists the generic elements"
Changed FHIR representation of Copy Receiver from "Patient/Organization" to "Patient/RelatedPerson/PractitionerRole"

**Comment by JBleuer** [comment]
Table 7 depicts basically the same information as visible in the questionnaire specification; but less profound and not detailed. Furthermore, there are differences in wording. It has to be discussed, if tab. 7 could be replaces by a descrition with a link to the questionnaire. 
----
Detail: Date of creation of the document is not depicted in the questionnaire.

**Comment by pjolo** [comment]
Good for me
