### ISSUE TITLE
Correct place in Composition? Extension vs. section:orderReferral.entry

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-orf#120]
* [antecedentEpisodeOfCare](http://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-composition-definitions.html#Composition.extension:antecedentEpisodeOfCare) vs. [entry:EpisodeOfCare](http://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-composition-definitions.html#Composition.section:orderReferral.entry:EpisodeOfCare)
* [patientConsent](http://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-composition-definitions.html#Composition.extension:patientConsent) vs. [entry:Consent](http://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-composition-definitions.html#Composition.section:orderReferral.entry:Consent)

What is the difference between these items? Are they the same? Where is the right place to map them?

**Comment by JBleuer** [comment]
Addendum: Discussion in Telco (Sept 22): We leave sections as is

**Comment by pjolo** [comment]
Ok and close the issue
