### ISSUE TITLE
 CH ORF Appointment.acctor is 1..1 but has to be 0..1

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-orf#132]
Issue derived from etoc #63 (https://github.com/hl7ch/ch-etoc/issues/63#issue-1441447287):
 CH ORF Appointment.acctor is 1..1 but has to be 0..1.

**Comment by JBleuer** [comment]
Committed but not visible due to problem with structure mapping

**Comment by pjolo** [comment]
Good for me
