### ISSUE TITLE
eroneuous entry in ch.fhir.ig.ch-orf.xml

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-orf#140]
Deleted:
resource>
      reference>
        reference value="QuestionnaireResponse/order-referral-form"/>
      </reference>
      name value=")"/>
      description value="Example for QuestionnaireResponse"/>
      exampleCanonical value="http://fhir.ch/ig/ch-orf/StructureDefinition/ch-orf-questionnaireresponse"/>
    </resource>

**Comment by JBleuer** [comment]
To discuss:
Do we want 3 different QR; e.g. QR Radiology Order could be dropped because we have a dedicated rad. order IG

**Comment by JBleuer** [comment]
As discussed at telco of 31.05.2023, we keep all 3 examples.

Added the following text to: home, ###### QuestionnaireResponse Resource

This Implementation Guide provides three examples of QuestionnaireResponse such as [QuestionnaireResponse Medical Referral](file:///Users/bleuer/Documents/GitHub/ch-orf/output/QuestionnaireResponse-qr-order-referral-form.html), [QuestionnaireResponse Radiology Order](file:///Users/bleuer/Documents/GitHub/ch-orf/output/QuestionnaireResponse-qr-radiology-order.html) and [QuestionnaireResponse External Diagnostics Order](file:///Users/bleuer/Documents/GitHub/ch-orf/output/QuestionnaireResponse-qr-external-diagnostics-order.html). Only [QuestionnaireResponse Medical Referral](file:///Users/bleuer/Documents/GitHub/ch-orf/output/QuestionnaireResponse-qr-order-referral-form.html) shows all items filled in.

**Comment by pjolo** [comment]
Good for me
