### ISSUE TITLE
Questionnaire Definition Elements do not resolve to fragment on html page

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-orf#144]
A Questionnaire Item can have a definition element, see https://hl7.org/fhir/R4/questionnaire-definitions.html#Questionnaire.item.definition:

The uri refers to an ElementDefinition in a [StructureDefinition](https://hl7.org/fhir/R4/structuredefinition.html) and always starts with the [canonical URL](https://hl7.org/fhir/R4/references.html#canonical) for the target resource. When referring to a StructureDefinition, a fragment identifier is used to specify the element definition by its id [Element.id](https://hl7.org/fhir/R4/element-definitions.html#Element.id). E.g. http://hl7.org/fhir/StructureDefinition/Observation#Observation.value[x]. In the absence of a fragment identifier, the first/root element definition in the target is the matching element definition.

However the IG Publisher can only resolve items directly to an URL address with a fragment where the fragment is only a singular datelement (not nested, not sliced, not an array):

e.g: https://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-composition.html#Composition.status

but not as detailed as it has been done in ORF:

output/Questionnaire-ch-orf-module-initiator.html#/html/body/div/div/div/div/div/div/table/tr/td/a at Line 283, column 1421	error	The link 'StructureDefinition-ch-orf-initiator.html#Extension.extension:ch-orf-personalrelation' for "Extension.extension:ch-orf-personalrelation" cannot be resolved (valid targets: 79 targets)

output/Questionnaire-ch-orf-module-initiator.html#/html/body/div/div/div/div/div/div/table/tr/td/a at Line 284, column 1414	error	The link 'StructureDefinition-ch-orf-initiator.html#Extension.extension:ch-orf-personalrelation' for "Extension.extension:ch-orf-personalrelation" cannot be resolved (valid targets: 79 targets)

output/Questionnaire-ch-orf-module-order.html#/html/body/div/div/div/div/div/div/table/tr/td/a at Line 284, column 1559	error	The link 'StructureDefinition-ch-orf-servicerequest.html#ServiceRequest.identifier:placerOrderIdentifier.value' for "ServiceRequest.identifier:placerOrderIdentifier.value" cannot be resolved (valid targets: 265 targets)

**Comment by oliveregger** [comment]
The Link points to 

https://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-initiator.html#Extension.extension:ch-orf-personalrelation

but on the page
[StructureDefinition-ch-orf-initiator-definitions.html#Extension.extension:ch-orf-personalrelation](https://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-initiator-definitions.html#Extension.extension:ch-orf-personalrelation)

the href target has -definitions inside the html, which provokes the error:

StructureDefinition-ch-orf-initiator***-definitions***.html#Extension.extension:ch-orf-personalrelation](https://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-initiator-definitions.html#Extension.extension:ch-orf-personalrelation)

**Comment by oliveregger** [comment]
https://build.fhir.org/ig/hl7ch/ch-orf/Questionnaire-ch-orf-module-initiator.html

**Comment by pjolo** [comment]
I had the same impression when I watched the qa yesterday. So I close the issue.
