### ISSUE TITLE
Missing elements in mapping from QR to Bundle

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-orf#15]
[Profile CH ORF Composition](http://build.fhir.org/ig/hl7ch/ch-orf/branches/master/StructureDefinition-ch-orf-composition.html)
- Composition.type
   - Precise type of clinical document
   - [ValueSet](http://fhir.ch/ig/ch-epr-term/ValueSet-DocumentEntry.typeCode.html)
- Composition.category
   - High-level kind of a clinical document at a macro level
   - [ValueSet](http://fhir.ch/ig/ch-epr-term/ValueSet-DocumentEntry.classCode.html)
- Composition.date
   - Composition editing time
- Composition.title
   -  Meaningful title

**Comment by oliveregger** [comment]
Composition.type und Composition.category müssen von den abgeleiteten Implementation Guides im Mapping definiert werden.

**Comment by oliveregger** [comment]
Composition.date äquivalen Bundle.timestamp setzen

**Comment by oliveregger** [comment]
Composition.title muss auch vom abgeleiteten Guide definiert werden.

**Comment by oliveregger** [comment]
we need to describe that in the ig

**Comment by ziegm** [comment]
Description in the IG needed: see also https://github.com/hl7ch/ch-orf/issues/31
