### ISSUE TITLE
Home: Meaning of MustSupport (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#154]
ch.fhir.ig.ch-orf#2.0.0-ballot /

The flag MustSupport is used in the IG but nowhere described was the meaning is

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
https://github.com/hl7ch/ch-core/wiki/Guidelines-for-Swiss-IG-Development#2-use-of-must-support

**Comment by ziegm** [comment]
Telco 18.10. PJ/JB/MH/OE/MZ:
Aktueller Gebrauch von MS: Elemente des Questionnaires die in den Resourcen gemappt werden

**Comment by JBleuer** [comment]
Added this text: In this implementation guide “Must support” (MS) denotes elements of the questionnaire that are mapped to corresponding resource items.

**Comment by pjolo** [comment]
Please add a title "MustSupport" so that the definition of MustSupport can be found quickly.

**Comment by ziegm** [comment]
@pjolo @JBleuer PR is merged

**Comment by pjolo** [comment]
Good
