### ISSUE TITLE
Terminology binding in service request (Beat Heggli)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#155]
ch.fhir.ig.ch-orf#2.0.0-ballot /

the terminology-binding in service_request (SNOMED-CT) should also be extended to CHOP code, as this is currently used

Beat Heggli

**Comment by ziegm** [comment]
https://github.com/hl7ch/ch-core/issues/125

**Comment by pjolo** [comment]
We have no termonology binding to SNOMED CT in the service request profile.
SNOMED is only used as an example terminology. See image:

![image](https://github.com/hl7ch/ch-orf/assets/87263053/16af6b55-687b-4d02-b178-2801f1f8f22b)

[Definition](https://www.hl7.org/fhir/terminologies.html#strength ) of example binding: Instances are not expected or even encouraged to draw from the specified value set. The value set merely provides examples of the types of concepts intended to be included.

This means if necessary CHOP can also be used as terminology here.

**Comment by pjolo** [comment]
Beat Heggli was informed.
