### ISSUE TITLE
Home - IG Fragments (Safety Considerations) (Patrick Jolo (eHealth Suisse))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#161]
ch.fhir.ig.ch-orf#2.0.0-ci-build /

In the recommended fragments, the section with the safety considerations as in CH Core is missing http://fhir.ch/ig/ch-core/index.html

Patrick Jolo (eHealth Suisse)

**Comment by ziegm** [comment]
It is already included: https://build.fhir.org/ig/hl7ch/ch-orf/branches/master/index.html#safety-considerations
