### ISSUE TITLE
Questionnaire is not yet mapped (QR -> Bundle)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-orf#17]
Composition.section.entry:
```
<entry>
    <reference value="http://example.com/fhir/Questionnaire/order-referral-form"/>
    <type value="Questionnaire"/>
</entry>
```

Bundle.entry:
```
<entry>
    <fullUrl value="http://example.com/fhir/Questionnaire/order-referral-form"/>
    <resource>
      <Questionnaire>
        <id value="order-referral-form"/>
```

Wenn der Questionnaire mittels UUID aus der Composition referenziert wird, passiert folgender Fehler:
`Questionnaire.url: Resource id/url mismatch: null/http://fhir.ch/ig/ch-orf/Questionnaire/order-referral-form`

**Comment by oliveregger** [comment]
kann via canonical url referenziert werden?

**Comment by oliveregger** [comment]
noch Fehlermeldung wegen canonical Referenzierung, sonst aber ok

**Comment by ziegm** [comment]
Fehlermeldung kommt auch nicht mehr
