### ISSUE TITLE
Home - Typo (Gabriel Hess, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#179]
ch.fhir.ig.ch-orf#3.0.0-ballot /

Typo in Kapitel 1: CH Orf statt CH ORF im zweitletztem Absatz

Gabriel Hess, BFH

**Comment by ziegm** [comment]
@pjolo please review the changes and approve the pr
- [home](https://build.fhir.org/ig/hl7ch/ch-orf/branches/issue179_typo/index.html)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-orf/branches/issue179_typo/changelog.html)

**Comment by pjolo** [comment]
The correction is good.
