### ISSUE TITLE
Cas d'application - Typos french (La Poste)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#182]
ch.fhir.ig.ch-orf#3.0.0-ballot /usecase-french.html

“Placer d’ordre” -> Donneur d’ordre
“Remplisseur d’ordre” -> Destinataire?

La Poste

**Comment by ziegm** [comment]
@pjolo please review the changes and approve the pr:
- [use case french](https://build.fhir.org/ig/hl7ch/ch-orf/branches/issue182_typos/usecase-french.html)
- [changelog](https://build.fhir.org/ig/hl7ch/ch-orf/branches/issue182_typos/changelog.html)

**Comment by pjolo** [comment]
The correction is good.
