### ISSUE TITLE
Module Questionnaire Coverage - extend accronyms (La Poste)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#183]
ch.fhir.ig.ch-orf#3.0.0-ballot /Questionnaire-ch-orf-module-coverage.html

Next to KVG Add LAMAL (French and Italian) source : Loi fédérale sur l'assurance-maladie (LAMal) (admin.ch)
 

Same for ZSR à RCC (French and Italian) source : ZSR Kurzversion - SASIS AG

La Poste

**Comment by pjolo** [comment]
I have discussed this issue with Pedro dos Santos.
The reason why abbreviations such as KVG, ZSR, IV, MV, etc. should be translated into French and Italian is that non-German speakers are increasingly having problems understanding them. Adding the translations in the “Text” column, e.g. KVG, LAMal, can be very helpful.

**Comment by pjolo** [comment]
@ziegm: See below the translations of the abbreviations
German | French  | Italian
-------- | -------- | --------
ZSR | RCC   | RCC
AHV   | AVS   | AVS
KVG | LAMal | LAMal
VVG | LCA | LCA
IV | AI | AI
MV | AM | AM

**Comment by ziegm** [comment]
@pjolo please review the changes:
* [Questionnaire](https://build.fhir.org/ig/hl7ch/ch-orf/branches/issue183_accronyms/questionnaire-form.html)
   * UVG additonal to your acronyms above 
* [Changelog](https://build.fhir.org/ig/hl7ch/ch-orf/branches/issue183_accronyms/changelog.html)

**Comment by pjolo** [comment]
The changes are good.
