### ISSUE TITLE
Epic Feedback for 2024 Ballot

### ISSUE THREAD

**Issue by katie-reynolds** [hl7ch/ch-orf#184]
Comments from review at Epic: 

On Home: 
The expectation that general workflow patterns of cross-organizational workflows for orders, referrals, and transitions of care are to be implemented using a form-based approach does not seem to follow the base HL7 FHIR recommendations that are found at https://build.fhir.org/workflow-module.html and which are currently further developed at https://confluence.hl7.org/pages/viewpage.action?pageId=248715046. We are particularly concerned that a form-based approach will negatively impact the healthcare providers who are users of our systems. This seems to be an attempt to retrofit a paper-based process in the guise of a computerized system without the benefits of the digital transformation that can benefit healthcare.

**Comment by katie-reynolds** [comment]
On Home (https://fhir.ch/ig/ch-orf/index.html#volume-1--implementation-guide): 
We agree that the use of questionnaire and questionnaire responses is not required to accomplish the use of FHIR for general workflow patterns.

**Comment by katie-reynolds** [comment]
On Home (https://fhir.ch/ig/ch-orf/index.html#volume-2--transactions):
There seems to be an unintended high bar for implementers by requiring the transmission of FHIR Transaction Bundles.  The processing of Transaction bundles is a capability that many systems will not allow for various technical and policy reasons. See previous comment for the recommended approaches for workflow interactions as described by HL7.

**Comment by katie-reynolds** [comment]
On Use Cases (https://fhir.ch/ig/ch-orf/usecase-english.html#appointments):
We agree with the observation that appointments are closely linked to various clinical workflows, and that scheduling appointments is tricky. We suggest reviewing the IHE ITI Scheduling profile for an approach to scheduling cross-organizational appointments (https://build.fhir.org/ig/IHE/ITI.Scheduling/)

**Comment by pjolo** [comment]
All open questions were answered and clarified with Katie Reynolds. There are no more open questions, so this issue can be closed.
