### ISSUE TITLE
Changelog: add date to the versions

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-orf#185]
Ballot feedback from Christoph Knöpfel:
Add the dates after the version in the changelog to unify between the different Swiss IGs.
See https://fhir.ch/ig/ch-core/changelog.html

**Comment by ziegm** [comment]
@pjolo please review the update and approve the PR
- [changelog](https://build.fhir.org/ig/hl7ch/ch-orf/branches/issue185_dateChangelog/index.html) with dates and issue as new entry

**Comment by pjolo** [comment]
Adaptation good
