### ISSUE TITLE
Error transforming Appointment for ch-rad-ord qr response

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-orf#28]
A ch-rad-order questionnaire response returns an exception for QuestionnaireResponse-QuestionnaireResponseRadiologyOrder.json

```
... Unknown input variable src in
http://fhir.ch/ig/ch-orf/StructureMap/OrfQrToBundle rule Appointment
(vars = source variables [grp: (BackboneElement)], target variables
[bundle: (Bundle), composition: (Composition), serviceRequest:
(ServiceRequest)], shared variables [])
```

**Comment by oliveregger** [comment]
- Mehrere Telefonnummern beim Patienten führen zu einem Fehlschlag der $extract-Operation. (Failed to call access method: org.hl7.fhir.exceptions.FHIRException: Exception executing transform value.value = (item.answer.value) on Rule \"patient.phone\": Rule \"patient.phone\": Evaluation of item.answer.value returned 2 objects)

**Comment by oliveregger** [comment]
PreviousResults von Rad-Order auch hier direkt hinzugefügt, Antrag das auch noch im ORF einzubinden.

https://github.com/hl7ch/ch-rad-order/issues/9

**Comment by ziegm** [comment]
At the end, please add the change to the log ([Change Log](https://github.com/hl7ch/ch-orf/blob/master/changelog.md))
