### ISSUE TITLE
Hyperlink verweist auf nicht existierende Seite (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#34]
ch.fhir.ig.ch-orf#0.10.0 /

Abschnitt "1.1.1.2 SDC Actors and workflow relevant to CH ORF": Der Hyperlink für den SDC Form Designer verweist mit http://build.fhir.org/ig/HL7/sdc/sdc-form-designer.html auf eine am 6.9.2021 nicht vorhandene Seite.

Emmanuel Eschmann, CISTEC AG

**Comment by ziegm** [comment]
See also: https://github.com/hl7ch/ch-orf/issues/32
