### ISSUE TITLE
Mehrfache Einbettung von FHIR Profil Differential Tables (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#42]
ch.fhir.ig.ch-orf#0.10.0 /

Unter http://fhir.ch/ig/ch-orf/index.html#servicerequest-resource, http://fhir.ch/ig/ch-orf/index.html#documentreference-resource und an weiteren Stellen weiter unten im selben Dokument werden die Differential Tables zu Profilen, die für den CH-ORF IG definiert wurden, eingebettet. Dieselben Differential Tables finden sich an anderer Stelle im IG (bei den Profil-Definitionen z.Bsp. http://fhir.ch/ig/ch-orf/StructureDefinition-ch-orf-servicerequest.html).
Vorschlag: Das bereits viele Bildschirmseiten lange Dokument http://fhir.ch/ig/ch-orf/index.html kürzen, indem hier auf die redundante Einbettung von Differential Tables verzichtet wird.

Emmanuel Eschmann, CISTEC AG

**Comment by EmmanuelEschmann** [comment]
@ziegm : Ja, vielen Dank, so hatte ich es gemeint.

**Comment by ziegm** [comment]
discussed at telco, okay
