### ISSUE TITLE
CH ORF Appointment.requestedPeriod (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#47]
ch.fhir.ig.ch-orf#0.10.0 /StructureDefinition-ch-orf-appointment.html

Wenn man im Questionnaire nur ein Startdatum angibt, sollte beim Mapping das Enddatum ebenso generiert werden.

Aktueller Fehler beim Validieren des Bundles:   
(Appointment): app-3: 'Only proposed or cancelled appointments can be missing start/end dates' Rule 'Only proposed or cancelled appointments can be missing start/end dates' 

Description im Profil:   
Single Date/time or Date/time interval indication for the appointment. A single Date/time indication MUST have the same value for start and end.

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
MZ: Solution reviewed, it's okay.

@PeroGrgic 
Please review the change and if it is okay, you can close this issue.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
