### ISSUE TITLE
CH ORF Appointment (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#48]
ch.fhir.ig.ch-orf#0.10.0 /StructureDefinition-ch-orf-appointment.html

Error if Appointment.status = "booked"
app-3: 'Only proposed or cancelled appointments can be missing start/end dates' 

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
[Appointment](http://build.fhir.org/ig/hl7ch/ch-orf/branches/issue48/StructureDefinition-ch-orf-appointment.html) (neuer Vorschlag)

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
