### ISSUE TITLE
CH ORF Composition.extension:copyReceiver (Walter Wellauer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#50]
ch.fhir.ig.ch-orf#0.10.0 /StructureDefinition-ch-orf-composition-definitions.html

http://fhir.ch/ig/ch-orf/StructureDefinition-ch-orf-composition-definitions.html#Composition.extension:copyReceiver
should
Reference(CH Core Organization Profile | CH Core Patient Profile | Related Person | CH Core Practitioner Profile)
reason:
copies of a referral might be of interest or essential also to related persons or family doctors or similar

Walter Wellauer, Cistec AG

**Comment by JBleuer** [comment]
Der Practioneer kann via Organization abgebildet werden; die related Person über Patient ist inhaltlich sicher nicht richtig, auch wenn es geht. Vorschlag: Erweiterung auf Related Person.

**Comment by walterwellauer** [comment]
Folgernd aus dem Entscheid zu #51 und aus dem ursprünglichen feedback müsste der copyReceiver m.E. Reference(CH Core Practitioner Profile | CH Core Patient | Related Person) haben. In der Praxis gehen Kopien sehr oft an den Hausarzt, RelatedPerson (Angehörige, Arbeitgeber, ...) oder eben den Patient. @JBleuer die Forderung, den Patienten über RelatedPerson abzubilden ist nie gestellt worden.

**Comment by ziegm** [comment]
Vorschlag, das entsprechend wie beim Selbstzahler zu machen (boolean an wen) -> Referenzen wie von Walter vorgeschlagen.

**Comment by ziegm** [comment]
Entscheid Telco: kann so gemacht werden

**Comment by ziegm** [comment]
@oliveregger : Bitte Mapping entsprechend anpassen

**Comment by oliveregger** [comment]
Questionnaire wurde noch angepasst weil * boolean nicht geht, jetzt ist eine 0..* Group für PractionierRole sowie RelatedPerson @lpg-tech @JBleuer

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
