### ISSUE TITLE
CH ORF Composition.extension:receiver (Walter Wellauer (Cistec AG))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#51]
ch.fhir.ig.ch-orf#0.10.0 /StructureDefinition-ch-orf-composition-definitions.html

http://fhir.ch/ig/ch-orf/StructureDefinition-ch-orf-composition-definitions.html#Composition.extension:receiver
should
Reference(CH Core Practitioner Profile | CH Core Practitioner)
reason:
Often a refferal is sent to a specific practitioner

Walter Wellauer (Cistec AG)

**Comment by walterwellauer** [comment]
Liebe @ziegm,
ich bin damit einverstanden - aber warum wird das dann beim Kopienempfänger nicht auch so gehandhabt #50? Diese müssten dann ja der Logik folgend  Reference(CH Core Practitioner Profile | CH Core Patient | Related Person) haben.

**Comment by ziegm** [comment]
@PeroGrgic 
If you agree, please close this issue.

**Comment by PeroGrgic** [comment]
Issue resolved and closed.
