### ISSUE TITLE
Questionnaire Order-Referral-Form (Tim Dorner, healthinal)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#52]
ch.fhir.ig.ch-orf#0.10.0 /questionnaire.html

In the Questionnaire i am not able to put in the coverage.payor for the following groups (coverage.iv & coverage.mv) This leads to an validation error.

Either it should be possible to add this the information coverage.payor to the groups. 

Or the second option would be to add those information by default  to the bundle everytime the coverage.iv.verfuegungsnummer or coverage.mv.verfuegungsnummer is entered. 

Tim Dorner, healthinal

**Comment by ziegm** [comment]
Telco: Vorschlag übernehmen

**Comment by ziegm** [comment]
@oliveregger : Bitte das Mapping entsprechend anpassen.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
