### ISSUE TITLE
Home (moritz strickler, post ch kommunikation ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#53]
ch.fhir.ig.ch-orf#0.10.0 /

1. Im Questionnaire ist die Kardinalität für den Patienten als 0...1 definiert. ME sollte aber der Patient zwingend sein und die Kardinalität somit 1..1.
2. Im Abschnitt "Appointment" stehen drei Status zur Verfügung. Ein zusätzliche Status "Abgelehnt" wäre hilfreich, falls der angefragt Serviceanbieter den Auftrag nicht durchführen kann.

moritz strickler, post ch kommunikation ag

**Comment by JBleuer** [comment]
"Abglehnt" ist nicht vorgesehen, da eine Order nicht mit "abgelehnt" gemacht wird. Ev. ist es aber trotzdem sinnvoll für den use case "Weiterleitung der Order zwischen mehreren Beteiligten beim Order Filler"? Ist zu diskutieren

**Comment by JBleuer** [comment]
Es ist denkbar, dass man eine Order ohne Patient macht (Test, Qualitätssicherung). Will man diesen use case abdecken?

**Comment by ziegm** [comment]
2. Ressourcen sind im Dokument, im Austauschformat (nicht im Workflow) -> muss nicht erweitert werden
    Würde allenfalls Workflow betreffen, dort aber anders abgebildet (Original ServiceRequest unverändert).
TBD: Mit Moritz besprechen.

**Comment by ziegm** [comment]
Feedback zu Punkt 2 von Moritz Strickler, 03.11.2021, per E-Mail:
"Eure Begründung ist nachvollziehbar und ich bin mit dem Entscheid einverstanden."

**Comment by ziegm** [comment]
Entscheid 17.11.: Patient Min-Kardinalität 1

**Comment by ziegm** [comment]
@pero:
Please review the change. If it is okay, please merge this [PR](https://github.com/hl7ch/ch-orf/pull/89) and close the issue.

**Comment by PeroGrgic** [comment]
Reviewed the changes. PR mergred and issue closed.
