### ISSUE TITLE
Anpassung Questionnaire (moritz strickler, post ch ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#54]
ch.fhir.ig.ch-orf#0.10.0 /

1. Ist es möglich wenn-dann-Bedingungen in den Formularen zu implementieren? Bspw. wenn Geschlecht M, dann wird nicht nach Schwangerschaft gefragt bzw. das Feld ausgeblendet.
2. Beim der Absender- und Empfängerorganisation wäre es hilfreich, wenn man die OID der Institution im Formular erfassen könnte.

moritz strickler, post ch ag

**Comment by ziegm** [comment]
Telco:
1. Questionnaire wird kontinuierlich angepasst. Schwangerschaft betrifft RAD-Order, whs.. auch LAB-Order, nicht CH ORF.
2. Aktuell über GLN/ZSR im Questionnaire abzubilden. Strukturiert kann die OID übermittelt werden. Somit keine Anpassung.

**Comment by ziegm** [comment]
MZ: Moritz Strickler per E-Mail über Entscheid informiert.

**Comment by ziegm** [comment]
@PeroGrgic : Please review and close the issue.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
