### ISSUE TITLE
Coverage Type (Felizitas Wahl-Homner. CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#55]
ch.fhir.ig.ch-orf#0.10.0 /ValueSet-ch-orf-vs-coveragetype.html

coverage.type
http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-coverage-definitions.html#Coverage.type
should have a binding on a swiss value set;

OKP	      Obl. Krankenversicherung
IV	              Invalidenversicherung
MV                Militärversicherung
UV	              Unfallversicherung
SZ	              Selbstzahler
Andere	       Andere
Unbekannt	Unbekannt
ZV	                Zusatzversicherung

Please consider, to use the abbreviations OKP, UV, MV, etc. as proposed , because it is common practice within the Swiss health system. 

For further information about BfS-Code, Definition and Display in FR,  IT or  EN please go to 
https://github.com/hl7ch/ch-core/issues/116 

Felizitas Wahl-Homner. CISTEC AG

**Comment by ziegm** [comment]
Current ValueSet in CH ORF: http://fhir.ch/ig/ch-orf/ValueSet-ch-orf-vs-coveragetype.html

Current Code & Display |  Proposal Code & Display
:-- | :--
KVG = According to KVG |  1 = Krankenversicherung (obligat.)
UVG = According to UVG |  4 = Unfallversicherung
VVG = According to VVG |  ?
IVG = According to IVG |  2 = Invalidenversicherung
MVG = According to MVG |  3 = Militärversicherung
Self = Self-payer |  5 = Selbstzahler (z.B. Ausländer ohne Grundversicherung)
Other = Other | 8 = andere
-- | 9 = unbekannt


[BFS](https://www.bfs.admin.ch/bfs/de/home/statistiken/kataloge-datenbanken/publikationen.assetdetail.7066232.html)
![image](https://user-images.githubusercontent.com/32767151/144189930-bda2b77a-ab20-4b74-a7b9-f6ba684497a8.png)

**Comment by JBleuer** [comment]
CoverageType: Codes werden so  belassen wie sie sind. Begründung: Die bestehenden Codes sind klarer, da sie auf die entsprechende Gesetzgebung verweisen Zudem ist die Bezeichnung "Zusatzversicherung" mehrfach besetzt und damit weniger klar.
Entscheid wird von Felizitas akzeptiert.

**Comment by PeroGrgic** [comment]
Issue ist ok und wird geschlossen.
