### ISSUE TITLE
CH ORF Coverage// Coverage.class.type (Felizitas Wahl-Homner, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#56]
ch.fhir.ig.ch-orf#0.10.0 /StructureDefinition-ch-orf-coverage.html // Value Set http://hl7.org/fhir/ValueSet/coverage-class

coverage.class.type
http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-coverage-definitions.html#Coverage.class.type
should have a binding on a swiss value set; 

A		        allgemein
HP		        halbprivat
P 	     	        privat
Unknown	unbekannt
Others		andere

Please consider, to use the abbreviations A, HP, P as proposed , because it is common practice within the Swiss health system. 

For more information about BfS-Code, Definition and Display in FR, IT or EN please go to 
https://github.com/hl7ch/ch-core/issues/116 

Felizitas Wahl-Homner, CISTEC AG

**Comment by ziegm** [comment]
* [Coverage.class.type](http://build.fhir.org/ig/hl7ch/ch-orf/branches/master/StructureDefinition-ch-orf-coverage-definitions.html#Coverage.class.type): The type of classification for which an insurer-specific class label or number and optional name is provided, for example may be used to identify a class of coverage or employer group, Policy, Plan.
   * The codes SHALL be taken from [CoverageClassCodes](http://hl7.org/fhir/R4/valueset-coverage-class.html) (Binding extensible)

Hier ist zu klären/besprechen, ob man im CH ORF die Angabe, was die Versicherung bezahlt (z.B. Allgemein, Privat), abbilden will. Wenn ja, müssten wir definieren, wie man Coverage.class abbilden will und wo man es im Questionnaire integrieren würde.

**Comment by JBleuer** [comment]
CoverageClassType entsspricht so etwas wie Art des Versicherungsanschlusses: Also Versicherung über die Firma oder über einen Verband abgeschlossen (z.B. Unfallversicherung der Firma) Bilden wir nicht ab. Mit der Aenderung gemäss Vorschlag von Felizitas würde die Bedeutung verändert. 
Zur Frage der Versicherungsdeckung: Auskunft von Beat Arnet, ehemals KPT. Bereichsleitung Leistungen und Mitglied der Geschäftsleitung: Gemäss ihm ist die Kostenübernahme heute sehr variabel; bsp. Flex Versicherungen.
Diese Variabiltät möchten wir bei der Zuweisung nicht abbilden, das wird zu kompliziert.
Es ist auch nicht nötig, da der Leistungserbringer eh eine Kostengutsprache einholt.
Felizitas akzeptiert den Entscheid.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
