### ISSUE TITLE
To discuss if one receiver organisation should provide n endpoints (with diffent ID's)

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-orf#58]

**Comment by ziegm** [comment]
Discussion with @JBleuer:
The idea was to support different endpoints (e.g. for different departments) for one recipient (e.g. hospital). Include as a feature request for a next version and do not currently implement, as it adds a complexity that is not currently necessary.

**Comment by ziegm** [comment]
@PeroGrgic please review the comment and if you agree, please close the issue.

**Comment by PeroGrgic** [comment]
I agree. The issue is closed.

**Comment by oliveregger** [comment]
is a feature request for the next version

**Comment by oliveregger** [comment]
Endpoints should be defined in a Health Care Provider Directory (e.g. IHE mCSD profile) and should no be part of CH-ORF, can we rediscuss this at the next telco?

**Comment by JBleuer** [comment]
Agree: The question is, if orf should allow for multiple endpoints for 
one receiver: My suggestion is "no" (at least for now) in oder to keep 
things simple: If somebody needs more than one endpoint, the 
organisation shall define multiple (technically independent) receivers.

Am 06.01.22 um 09:41 schrieb Oliver Egger:

**Comment by oliveregger** [comment]
discussion at telco: the endpoint does not need to be in the form, should be provided by a directory, will not be implemented.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
