### ISSUE TITLE
Questionnaire Order-Referral-Form marital Status (Walter Wellauer, Cistec AG )

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#60]
ch.fhir.ig.ch-orf#0.10.0 /questionnaire.html

martitalStatus to be integrated in ORF Questionnaire and its descendants, especially also eToc (desired by Axsana Health Link for use case Spitex Anmeldung)

Walter Wellauer, Cistec AG

**Comment by oliveregger** [comment]
Diskussion 17.11 PG/PJ/OE/JB/MH: 
- Im Beispiel abbilden
- Integration Questionnaire (patient.maritalStatus) (inkl. Mapping)

**Comment by ziegm** [comment]
Add marital status to:
* [Questionnaire](http://build.fhir.org/ig/hl7ch/ch-orf/branches/issue60/Questionnaire-order-referral-form.html): item patient.maritalStatus
* QuestionnaireResponse example [Order-Referral-Form](http://build.fhir.org/ig/hl7ch/ch-orf/branches/issue60/QuestionnaireResponse-qr-order-referral-form.json.html)
* Bundle example [Order-Referral-Form](http://build.fhir.org/ig/hl7ch/ch-orf/branches/issue60/Bundle-bundle-order-referral-form.json.html)
* Patient example [Erika Musterfrau](http://build.fhir.org/ig/hl7ch/ch-orf/branches/issue60/Patient-ErikaMusterfrau.html)

**Comment by ziegm** [comment]
@oliveregger : please update the mapping

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
