### ISSUE TITLE
Questionnaire Order-Referral-Form encounter.participant.type and individual (Walter Wellauer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#61]
ch.fhir.ig.ch-orf#0.10.0 /questionnaire.html

encounter.participant.type and  encounter.participant.individual to be integrated in ORF Questionnaire and its descendants, especially also eToc (desired by Axsana Health Link for use case Spitex Anmeldung where encounter.participant.type == PCP (Hausarzt) is nedded)

This information is generelly known on encounter level in a hospital level (by actor Questionnaire Filler)

Walter Wellauer, Cistec AG

**Comment by oliveregger** [comment]
Diskussion 17.11 PG/PJ/OE/JB/MH:
Zusätzliche Klärung, muss der Hausarzt noch angegeben werden? Juerg

**Comment by JBleuer** [comment]
Family Doctor is important to know; e.g. in case where the sender of the order is not the family doctor: Use Case: Home care is needed after discharge from hospital; order for home care is made by hospital hp but homecare needs to know who is the family doctor. 
However, in such a case, the family doctor is not a participant of the home care visit (he is not a encounter.participant). Therefore, the famiy doctor data is in:
Patient.generalPractitioner) Patient's nominated primary care provider

**Comment by pjolo** [comment]
taken note and issue closed.
