### ISSUE TITLE
Questionnaire Order-Referral-Form (Peter Janes)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#62]
ch.fhir.ig.ch-orf#0.10.0 /questionnaire.html

"orderIdnetifier" highly recommended (most likely uuid), in addition to placerOrderIdentifier (e.g. sending PIS local id) and fillerOrderIdnetifier (e.g. receiving KIS local id); example would be helpful for better understanding

Peter Janes

**Comment by ziegm** [comment]
MZ: Asked Peter Janes what exactly is meant by that.

**Comment by ziegm** [comment]
Rückfrage bei Peter Janes:

Es braucht folgende Identifier im eTOC:
- Fall-Id im Gesamtkontext (ist wahrscheinlich eine uuid)
- Patienten-Id, Fall-Id des sendende Systems
- Patienten-Id, Fall-Id des empfangenden Systems

**Comment by ziegm** [comment]
Anmerkungen:
1. Fall-ID bisher nicht abgebildet. Was heisst im Gesamtkontext (Sender vs. Empfänger)?
2. Patienten-ID als patient.localPid im Questionnaire abgebildet, Fall-ID nicht abgebildet
3. Der Auftraggeber kennt beim Ausfüllen des Auftrags diese Angaben unter Umständen nicht.

**Comment by ziegm** [comment]
Besprechung Telco 15.12. (JB, MH, PG, PJ, OE, MZ):
1. @PeterJanes: Kannst du uns ein konkretes Beispiel zur Verfügung stellen, wo das so gemacht wird? Uns sind bis jetzt keine bekannt.
2. Fall-ID ist aus unserer Sicht intern, muss nicht ausgetauscht werden. Verknüpfung via Auftragsnummer gegeben.

**Comment by ziegm** [comment]
Telco 14.01.2022 mit Dick Driessen, Peter Janes, Michaela Ziegler (und Juerg Bleuer):

**Besprechung/Walkthrough eTOC / Zuweisung Basis**
Fazit:
1. Identifier im Gesamtkontext -> Für die Rückverfolgbarkeit im Gesamtkontext kann die Auftragsnummer des Auftraggebers (order.placerOrderIdentifier -> ServiceRequest.identifier:placerOrderIdentifier) eingesetzt werden, somit keine Anpassung notwendig.
2. Sender: Lokale Patienten-ID (patient.localPid -> Patient.identifier:LocalPid) ist bereits abgebildet. Fall-ID ebenfalls nicht für den Austausch notwendig, da Verknüpfung via Auftragsnummer gegeben ist. Auch keine Anpassung notwendig.
3. Empfänger: Diese Angaben sind unter Umständen nicht bekannt. Für den Austausch nicht notwendig, ebenfalls keine Anpassung.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
