### ISSUE TITLE
Questionnaire Order-Referral-Form Patient.maritalStatus (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#63]
ch.fhir.ig.ch-orf#0.10.0 /

Patient.maritalStatus to be integrated in ORF Questionnaire and its descendants, especially also eTOC (desired for HealthLink for use case Spital -> Spitex Anmeldung)

Dick Driessen, axsana

Dick Driessen / axsana

**Comment by oliveregger** [comment]
will be closed, same as #60
