### ISSUE TITLE
Questionnaire Order-Referral-Form Patient.language (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#64]
ch.fhir.ig.ch-orf#0.10.0 /

Patient.language to be integrated in ORF Questionnaire and its descendants, especially also eTOC (desired for HealthLink for use case Spital -> Spitex Anmeldung)

Dick Driessen / axsana

**Comment by oliveregger** [comment]
Diskussion 17.11 PG/PJ/OE/JB/MH: 

- Im Beispiel abbilden
- Integration Questionnaire (patient.languageOfCorrespondance) (inkl. Mapping)

ValueSet für welche Sprachen?

**Comment by ziegm** [comment]
Add language of correspondance to:
* [Questionnaire](): item patient.languageOfCorrespondance
* QuestionnaireResponse example [Order-Referral-Form]()
* Bundle example [Order-Referral-Form]()
* Patient example [Erika Musterfrau]()

**Comment by ziegm** [comment]
@oliveregger : Please update the mapping

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
