### ISSUE TITLE
Questionnaire Order-Referral-Form Practitioner.identifier:ZSR (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#65]
ch.fhir.ig.ch-orf#0.10.0 /

Practitioner.identifier:ZSR to be integrated in ORF Questionnaire and its descendants, especially also eTOC (desired for HealthLink for use case Spital -> Spitex Anmeldung)

Dick Driessen / axsana

**Comment by ziegm** [comment]
* Questionnaire: add following items
   * receiver.practitioner.zsr
   * sender.author.practitioner.zsr
* Add example ZSR (A123262) for Dr. med. Hans Röntgen
   * QuestionnaireResponse-order-referral-form
   * Bundle-order-referral-form
   * Practitioner-HansRoentgen
* Add example ZSR (A123321) for Dr. med. Sabine Meier
   * QuestionnaireResponse-order-referral-form
   * Bundle-order-referral-form
   * Practitioner-SabineMeier

**Comment by ziegm** [comment]
During validation, there are [error messages](http://build.fhir.org/ig/hl7ch/ch-orf/branches/issue65/qa.html#_scratch_ig-build-temp-O8DJI4_repo_fsh-generated_resources_QuestionnaireResponse-qr-order-referral-form) for the new items.

Eruation:
- The items are generated in the questionnaire (spelling checked).
- When removing the items from the QR, the errors disappear.
- The items in the QR are not in the positions listed in the error.
- ???

**Comment by ziegm** [comment]
@oliveregger 
- Please update the mapping
- Do you have any other ideas about the errors?

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
