### ISSUE TITLE
Questionnaire Order-Referral-Form PractitionerRole.availableTime (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#66]
ch.fhir.ig.ch-orf#0.10.0 /

PractitionerRole.availableTime (PractitionerRole.availableTime.daysOfWeek, PractitionerRole.availableTime.allDay, PractitionerRole.availableTime.availableStartTime, PractitionerRole.availableTime.availableEndTime) to be integrated in ORF Questionnaire and its descendants, especially also eTOC (desired for HealthLink for use case Spital -> Spitex Anmeldung)

Dick Driessen / axsana

**Comment by oliveregger** [comment]
Diskussion 17.11 PG/PJ/OE/JB/MH: Erreichbarkeit vom Absender (OrderPlacer)?  FeatureRequest für eine nächste Version.

**Comment by JBleuer** [comment]
So far not implemented; would be yet another administrative item. To be discussed

**Comment by JBleuer** [comment]
Todays phonecall with Dick Driessen: Complex in implemenation and yet antother adminsitrative item. Dick agrees that we will not implement it now.

**Comment by pjolo** [comment]
taken note and issue closed.
