### ISSUE TITLE
Questionnaire Order-Referral-Form purpose.aim (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#67]
ch.fhir.ig.ch-orf#0.10.0 /

Purpose.aim to be integrated in ORF Questionnaire and its descendants, especially also eTOC (desired for HealthLink for use case Spital -> Spitex Anmeldung)

Dick Driessen / axsana

**Comment by ziegm** [comment]
Liebe Michaela

Entschuldigung, ich habe zwei fehlerhafte Change Proposals eingereicht:

* purpose.aim
* reason.statement
 
Könntest du diese beide Proposals löschen?

Entschuldigung die Umstände.

LG Dick
