### ISSUE TITLE
Questionnaire Order-Referral-Form adaption for eToc needs? (Walter Wellauer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#70]
ch.fhir.ig.ch-orf#0.10.0 /questionnaire.html

The needs in the CH eToc regarding https://github.com/hl7ch/ch-etoc/issues/19 and https://github.com/hl7ch/ch-etoc/issues/17 might have impact on CH ORF or alernatively CH eToc is developed separately from CH ORF to support those needs

Walter Wellauer, Cistec AG

**Comment by oliveregger** [comment]
- hl7ch/ch-etoc#19: expression based population can be added to ch-orf if we have input how to that (PR?), this does not conflict with ch-order
- hl7ch/ch-etoc#17: modularizing questionnaires could be a valuable approach, will be available with next version of sdc, but increases the complexity with having to support the $assembly operation or having tooling available (none yet to my knowledge) to create it.

**Comment by oliveregger** [comment]
summary:
- There is not yet a newer SDC version (except the current, 2.8.0 or now 3.0.0 ci-build) but we can upgrade as soon as a new version is out
- Questionnaire Support for expression based population and modularizing of ORF (and dependent) would be very helpful for a future version

**Comment by oliveregger** [comment]
@walterwellauer during the fhir connectathon 29 the last two days there was further discussion how to modularize questionnaires, the next sdc version will have first indications how to employ it. i would suggest to add it this issue also to open issues / feature request for the next version, see https://build.fhir.org/ig/hl7ch/ch-orf/openissues.html

**Comment by ziegm** [comment]
07.02.2024: PJ/JB/MH/MZ
https://hl7.org/fhir/uv/sdc/STU3/ is published in the meantime, can/should we continue with this issue then @oliveregger ?

**Comment by oliveregger** [comment]
I think we can close this issue, we integrated modular questinnaires based on SCD 3.0.0

**Comment by JBleuer** [comment]
This issue addresses two topics: 
1) Expression based population which was addressed in https://github.com/hl7ch/ch-etoc/issues/19   and subsequently added to ch-orf as  #82.
2) Restrict Questionnaire to information needed to display to the end user https://github.com/hl7ch/ch-etoc/issues/17: It was then disussec that modularizing questionnaires could be a valuable approach, feature not yet available at the time of disussion. Meanwhile, orf and its decedants are modularized; however this did not solve the issue "Restrict Questionnaire to information needed to display".
Conclusion of the discussion with Oliver:
We close #70 (this issue). 
1) is still addressed in #82 and https://github.com/hl7ch/ch-etoc/issues/19.
2) for "Restrict Questionnaire to information needed to display to the end user (Original feature request see https://github.com/hl7ch/ch-etoc/issues/17)", see #169
