### ISSUE TITLE
Questionnaire Order-Referral-Form Relationship initiator (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#71]
ch.fhir.ig.ch-orf#0.10.0 /

For the use case "Spital -> Spitex Anmeldung" the information concerning the relationship of the initiator to the patient ist required. This should incuded in the ORF Questionnaire and its descendants, especially also eTOC

The following releationships are required (Valuesets):
•	Spouse
•	Life partner
•	Daughter
•	Son
•	Brother
•	Sister
•	Mother
•	Father
•	Other family member
•	Acquaintance
•	Legal representatives
•	Other

 I could not find such a profile in CH:CORE, therefore this request is without concrete profile.

Dick Driessen / axsana

**Comment by oliveregger** [comment]
Diskussion 17.11 PG/PJ/OE/JB/MH: Abbildung Initiator via Kontaktperson (RelatedPerson)? Siehe http://build.fhir.org/ig/hl7ch/ch-orf/Questionnaire-order-referral-form.html, Juerg

**Comment by JBleuer** [comment]
Added Initiator and his relationship to to the patient (legal and personal relation can be

**Comment by pjolo** [comment]
Checked and issue closed.
