### ISSUE TITLE
Questionnaire Order-Referral-Form Consent Patient (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#72]
ch.fhir.ig.ch-orf#0.10.0 /

For the HealthLink user case "Spital - Spitex Anmeldung" the consent of the patient is required and this confirmation shall be transfered to the Spitex Organisation ("Der Kunde/die Kundin ist über die Anmeldung informiert und einverstanden" / Ja-Nein)

I could not find such a profile, therefor this ticket is without concrete profile request.

This profile is to be integrated in ORF Questionnaire and its descendants, especially also eTOC.

Dick Driessen / axsana

**Comment by oliveregger** [comment]
For the first version it was decided to leave Consent out of scope (19 May 2021)
