### ISSUE TITLE
Questionnaire Order-Referral-Form Date Discharge Hospital (Dick Driessen)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#73]
ch.fhir.ig.ch-orf#0.10.0 /

For the HealthLink user case "Spital - Spitex Anmeldung" the date when the patient will be discharged from the hospital is required. I could not find such a profile, therefor this ticket is without concrete profile request.

This profile is to be integrated in ORF Questionnaire and its descendants, especially also eTOC.

Dick Driessen

**Comment by oliveregger** [comment]
Diskussion 17.11 PG/PJ/OE/JB/MH:
Focus CH-eTOC nicht ORF, kann ev mit Appointment gelöst werden, Juerg fragt nach

**Comment by JBleuer** [comment]
Added Entry date, discharge Date and Organization of stationary episode antecedent to requested service (e.g spitex)

**Comment by pjolo** [comment]
Checked and issue closed.
