### ISSUE TITLE
Questionnaire Order-Referral-Form Spitex Type (Dick Driessen / axsana)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#74]
ch.fhir.ig.ch-orf#0.10.0 /

For the HealthLink user case "Spital - Spitex Anmeldung" the type of Spitex required for the patient is required (child-spitex, longterm, acute transitional care). I could not find such a profile, therefor this ticket is without concrete profile request.

This profile is to be integrated in ORF Questionnaire and its descendants, especially also eTOC.

Dick Driessen / axsana

**Comment by oliveregger** [comment]
Diskussion 17.11 PG/PJ/OE/JB/MH: Für was wird dies gebraucht? Wieso muss im Order der Typ der Organisation mitgegeben werden, der sollte doch bekannt sein ? Juerg fragt nach.

**Comment by JBleuer** [comment]
Will be addressed in CH eTOC

**Comment by pjolo** [comment]
Taken note and issue closed.
