### ISSUE TITLE
Selbstzahler

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-orf#80]
Der Use Case:

Leistung des HP wird von Versicherung nicht gedeckt; bezahtl wird sie aber nich vom Patienten sondern Vater, Freund etc.:

Läuft unter "Selbstzahler", auch wenn die Rechnung in diesem Fall nicht vom Patient selbst bezahlt wird.

Vorschlag zur Abbildung:

Die Resource Coverage hat im Original:

Diese related Person ist in CH ORF Coverage nicht mehr drin.

Man müsste wohl ei CH Core Related Person machen.
CH Core Related Person  in CH ORF Coverage wieder einfügen.

Hinweis auf Gestaltung des Questionnaires: Auswahlbox: Selbst, Andere Person.
Sebst --> Population mit Pat Name, Adresse etc.; Andere Person: Leer für händische Eingabe.
Umsetzung in ORF

_Originally posted by @JBleuer in https://github.com/hl7ch/ch-rad-order/issues/11#issuecomment-959656154_

**Comment by ziegm** [comment]
Anpassungen:
* Questionnaire: coverage.self
* Coverage Beispiele
   * Coverage Self Patient
   * Coverage Self RelatedPerson
* Profil: Coverage.payor -> zusätzlich Referenz zu RelatedPerson

**Comment by ziegm** [comment]
TBD @oliveregger : Bitte das Mapping entsprechend anpassen

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
