### ISSUE TITLE
Es kann immer nur ein Empfänger für eine Zuweisung angegeben werden: According to mail from Moritz (05.11.21): leave as is

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-orf#81]
According to mail from Moritz (05.11.21): leave as is

Moritz: Zu den Empfänger:
Ich denke, wir können mit den Kopie-Empfänger arbeiten.

_Originally posted by @JBleuer in https://github.com/hl7ch/ch-etoc/issues/23#issuecomment-962576622_

**Comment by ziegm** [comment]
@PeroGrgic please review

**Comment by PeroGrgic** [comment]
Agreed. The issue is closed.
