### ISSUE TITLE
Frage zu Abschnitt "Kopienempfänger" im Formular (Moritz Strickler, Clarisse Loechleiter, Post CH Kommunkation AG) #21 #24

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-orf#84]
Issue aus Rad-Order:
Empfänger von Auftrag und Resultat. Wird in ORF noch deutlicher beschrieben. Auch im eTOC und Rad-order beschreiben.

Siehe auch entsprehender Eintrag in RAD-Order: hl7ch/ch-rad-order#21 (comment) und eTOC

**Comment by JBleuer** [comment]
Pointed to the fact, that a copyreceiver shall receive a copy ot this order and all results therefrom.
See branch copy_receiver. If ok; please merge, I will then update Rad-Order and eTOC

**Comment by PeroGrgic** [comment]
Issues reviewed and closed.
