### ISSUE TITLE
Desired Accomodation: Use existing ValueSet (Michaela Ziegler (ahdis ag))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#91]
ch.fhir.ig.ch-orf#0.10.0 /StructureDefinition-ch-orf-encounter.html

Instead of defining an own ValueSet (http://fhir.ch/ig/ch-orf/ValueSet/ch-orf-vs-desiredaccommodation), the already existing ValueSet (http://fhir.ch/ig/ch-core/ValueSet-bfs-medstats-21-encountertype.html) should be used.

CH ORF current | CH Core
:-- | :--
P = Private | 3= privat
SP = Semi-private | 2 = halbprivat 
W = Ward | 1= allgemein
-- | 9 = unbekannt (wenn dieser Wert nicht im CH ORF verwendet werden soll, VS von bestehenden CS in CH Core erstellen)

**Comment by ziegm** [comment]
Entscheid Telco: VS definieren mit den Codes 3, 2, 1.

**Comment by ziegm** [comment]
@oliveregger : Bitte Mapping noch entsprechend anpassen.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
